# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Development

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Development
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm install @dontcode/core@latest --no-optional
          npm ci
      - name: Build
        run: |
          npm run nx run common:build -- --prod
          npm run nx run basic:build -- --prod
          npm run nx run screen:build -- --prod
#      - uses: actions/upload-artifact@v1
#        with:
#          name: distribution
#          path: node/dist/libs/core
      - name: Unit tests
        run: |
          npm run nx run common:test
          npm run nx run screen:test
          npm run nx run basic:test
