# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Development

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Development
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm --version
          npm install @dontcode/core@latest --no-optional
          npm ci
      - name: Build
        run: |
          npm run nx run common:build -- --prod
          npm run nx run sandbox:build -- --prod
          npm run nx run basic:build -- --prod
          npm run nx run screen:build -- --prod
          npm run nx run fields:build -- --prod
#      - uses: actions/upload-artifact@v1
#        with:
#          name: distribution
#          path: node/dist/libs/core
      - name: Unit tests
        run: |
          npm run nx run common:test
          npm run nx run sandbox:test
          npm run nx run screen:test
          npm run nx run basic:test
          npm run nx run fields:test
          npm run nx run plugin-tester:test
      - name: E2E Tests on ${{matrix.browser}}
        run: |
          npm run ng e2e -- --project=plugin-tester-e2e --browser ${{matrix.browser}}
      - uses: actions/upload-artifact@v2
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/plugin-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/plugin-tester-e2e/videos
