# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          npm --version
          npm install @dontcode/core@latest
          npm ci
      - name: Version
        if: ${{ matrix.browser == 'chromium' }}
        run: npm version patch
        working-directory: libs/common
      - name: Version
        if: ${{ matrix.browser == 'chromium' }}
        run: npm version patch
        working-directory: libs/sandbox
      - name: Version
        if: ${{ matrix.browser == 'chromium' }}
        run: npm version patch
        working-directory: libs/screen
      - name: Version
        if: ${{ matrix.browser == 'chromium' }}
        run: npm version patch
        working-directory: libs/basic
      - name: Version
        if: ${{ matrix.browser == 'chromium' }}
        run: npm version patch
        working-directory: libs/fields
      - name: Build
        run: |
          npm run nx run common:build -- --prod
          npm run nx run sandbox:build -- --prod
          npm run nx run basic:build -- --prod
          npm run nx run fields:build -- --prod
          npm run nx run screen:build -- --prod
      - name: Unit tests
        run: |
          npm run nx run common:test
          npm run nx run sandbox:test
          npm run nx run screen:test
          npm run nx run basic:test
          npm run nx run fields:test
      - name: E2E Tests on ${{matrix.browser}}
        run: |
          npm run ng e2e -- --project=plugin-tester-e2e --browser ${{matrix.browser}}
      - uses: actions/upload-artifact@v2
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/plugin-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/plugin-tester-e2e/videos
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: libs/basic
      - name: Push
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git commit -a -m "New release ${{steps.package-version.outputs.current-version}}" --allow-empty
          git push
      - name: Publish Common
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: |
          npm publish dist/libs/common --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Sandbox
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: npm publish dist/libs/sandbox --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Screen
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: npm publish dist/libs/screen --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Basic
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: npm publish dist/libs/basic --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Fields
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        run: npm publish dist/libs/fields --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Rebuild for deploy
        if: ${{ success() && matrix.browser == 'chromium'}}
        run: npm run build -- --prod --project=plugin-tester --base-href "https://dont-code.net/standard-plugins/"
      - name: Deploy PluginTester
        if: ${{ success() && ( matrix.browser == 'chromium' )}}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/apps/plugin-tester

