# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Common & Sandbox Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release, if needed (x.y.z-p)
        required: false
        type: string
      next:
        description: Is it a dev/next release ?
        required: true
        type: boolean

jobs:
  build:
    env:
      branch: ${{ inputs.next == true && 'Development' || 'main' }}
      stage: ${{ inputs.next == true && 'next' || 'latest' }}
      version: ${{ inputs.next == true && 'patch' || 'minor' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dont-code/plugins
          path: plugins
          fetch-depth: 0
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
      - name: Setup build environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: plugins/package-lock.json
      - run: npm install -g nx
      - name: Version
        if: ${{ ( matrix.browser == 'chromium' ) && ( inputs.version == '') }}
        run: |
          PACKAGE_VERSION=$(npm view @dontcode/plugin-common versions --json | jq -r '.[-1]')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          cd libs/common
          npm version $PACKAGE_VERSION --allow-same-version
          cd ../sandbox
          npm version $PACKAGE_VERSION --allow-same-version
        working-directory: 'plugins'
      - name: Version ${{env.version}}
        if: ${{ ( matrix.browser == 'chromium' ) && ( inputs.version == '') }}
        run: |
          cd libs/common
          npm version ${{env.version}}
          cd ../sandbox
          npm version ${{env.version}}
        working-directory: 'plugins'
      - name: Version
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.version != '') }}
        run: |
          PACKAGE_VERSION=${{inputs.version}}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          cd libs/common
          npm version $PACKAGE_VERSION
          cd ../sandbox
          npm version $PACKAGE_VERSION
        working-directory: 'plugins'
      - name: Install ${{env.stage}}
        run: |
          npm ci
          npm install @dontcode/core@${{env.stage}} --no-optional
        working-directory: 'plugins'
      - name: Build
        run: |
          nx run common:build:production
          nx run sandbox:build:production
        working-directory: 'plugins'
      - name: Unit tests
        run: |
          nx run common:test
          nx run sandbox:test
          nx run screen:test
          nx run basic:test
          nx run fields:test
          nx run plugin-tester:test
        working-directory: 'plugins'
      - run: |
          nx run plugin-tester-e2e:e2e --browser ${{matrix.browser}}
        working-directory: 'plugins'
      - uses: actions/upload-artifact@v3
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: plugins/dist/cypress/apps/plugin-tester-e2e/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: plugins/dist/cypress/apps/plugin-tester-e2e/videos
      - name: Building all plugins
        run: nx run plugin-tester:build:production --base-href "https://dont-code.net/plugins/"
        working-directory: 'plugins'
      - name: Publish libraries ${{env.stage}}
        if: ${{ success() && ( matrix.browser == 'chromium' ) }}
        run: |
          npm publish plugins/dist/libs/common --access public --tag ${{env.stage}}
          npm publish plugins/dist/libs/sandbox --access public --tag ${{env.stage}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
