# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Merge
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git merge origin/Development --strategy=recursive --strategy-option=theirs
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm install @dontcode/core@latest
          npm ci
      - name: Version
        run: npm version patch
        working-directory: libs/common
      - name: Version
        run: npm version patch
        working-directory: libs/screen
      - name: Version
        run: npm version patch
        working-directory: libs/basic
      - name: Version
        run: npm version patch
        working-directory: libs/fields
      - name: Build
        run: |
          npm run nx run common:build -- --prod
          npm run nx run basic:build -- --prod
          npm run nx run fields:build -- --prod
          npm run nx run screen:build -- --prod
      - name: Unit tests
        run: |
          npm run nx run common:test
          npm run nx run screen:test
          npm run nx run basic:test
          npm run nx run fields:test
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: libs/basic
      - name: Push
        run: |
          git commit -a -m "New release ${{steps.package-version.outputs.current-version}}"
          git push
      - name: Publish Common
        run: npm publish dist/libs/common --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Screen
        run: npm publish dist/libs/screen --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Basic
        run: npm publish dist/libs/basic --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Fields
        run: npm publish dist/libs/fields --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
