# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sandbox Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release, if needed (x.y.z)
        required: false
        type: string
  push:
    branches: [ main ]
    paths:
      - '*'
      - 'libs/sandbox/**'
      - '.github/workflows/release-sandbox.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*'
      - 'libs/sandbox/**'
      - '.github/workflows/release-sandbox.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dont-code/plugins
          path: plugins
          fetch-depth: 0
          ref: 'main'
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
      - name: Setup build environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: plugins/package-lock.json
      - name: Version
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( github.event.inputs.version == '') }}
        run: |
          PACKAGE_VERSION=$(npm dist-tag ls @dontcode/plugin-sandbox | grep -Po '(?<=next: ).*')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          cd libs/sandbox
          npm version $PACKAGE_VERSION
          npm version patch
        working-directory: 'plugins'
      - name: Version
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( github.event.inputs.version != '') }}
        run: |
          PACKAGE_VERSION=${{inputs.version}}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          cd libs/sandbox
          npm version $PACKAGE_VERSION
        working-directory: 'plugins'
      - name: Install
        run: |
          npm install -g nx
          npm install --force
          npm install @dontcode/core@latest --no-optional
        working-directory: 'plugins'
      - name: Build
        run: |
          nx run sandbox:build:production
        working-directory: 'plugins'
      - name: Tests
        run: |
          nx run sandbox:test
          nx run plugin-tester-e2e:e2e --browser ${{matrix.browser}}
        working-directory: 'plugins'
      - uses: actions/upload-artifact@v3
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: plugins/dist/cypress/apps/plugin-tester-e2e/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: plugins/dist/cypress/apps/plugin-tester-e2e/videos
      - name: Publish
        if: ${{ success() && ( matrix.browser == 'chromium' ) }}
        run: |
          npm publish plugins/dist/libs/sandbox --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ReVersion
        run: |
          npm version prerelease
        working-directory: 'plugins/libs/sandbox'
      - name: ReBuild
        run: |
          nx run sandbox:build:development
        working-directory: 'plugins'
      - name: RePublish
        if: ${{ success() && ( matrix.browser == 'chromium' ) }}
        run: |
          npm publish plugins/dist/libs/sandbox --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
