# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fields Release

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '*'
      - 'libs/fields/**'
      - '.github/workflows/release-fields.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '*'
      - 'libs/fields/**'
      - '.github/workflows/release-fields.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dont-code/plugins
          path: plugins
          fetch-depth: 0
          ref: 'main'
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
      - name: Setup build environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: plugins/package-lock.json
      - name: Install
        run: |
          npm install -g nx
          npm install --force
          npm install @dontcode/core@latest --no-optional
        working-directory: 'plugins'
      - name: Build
        run: |
          nx run fields:build:production
        working-directory: 'plugins'
      - name: Tests
        run: |
          nx run fields:test
          nx run plugin-tester-e2e:e2e --browser ${{matrix.browser}}
        working-directory: 'plugins'
      - uses: actions/upload-artifact@v3
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: plugins/dist/cypress/apps/plugin-tester-e2e/screenshots
          # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: plugins/dist/cypress/apps/plugin-tester-e2e/videos
